<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>info.quantlab</groupId>
	<artifactId>computational-finance-termstructuremodelplugins-project</artifactId>
	<version>0.0.3-SNAPSHOT</version>

	<name>Computational Finance - Project - Extend and Analyse a Term Structure Model</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<src.main.java.dir>src/main/java</src.main.java.dir>
		<src.test.java.dir>src/test/java</src.test.java.dir>
		<java.version>17</java.version>
		<finmath-lib.version>6.0.19</finmath-lib.version>
		<finmath-plot.version>0.5.1</finmath-plot.version>
		<junit.jupiter.version>5.6.2</junit.jupiter.version>
		<!-- maven plugins -->
		<compiler-plugin.version>3.8.1</compiler-plugin.version>
		<maven.javadoc-plugin.version>3.3.2</maven.javadoc-plugin.version>
		<maven.surefire-plugin.version>3.0.0-M5</maven.surefire-plugin.version>
		<maven.checkstyle-plugin.version>3.6.0</maven.checkstyle-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>net.finmath</groupId>
			<artifactId>finmath-lib</artifactId>
			<version>${finmath-lib.version}</version>
		</dependency>

		<dependency>
			<groupId>net.finmath</groupId>
			<artifactId>finmath-lib-plot-extensions</artifactId>
			<version>${finmath-plot.version}</version>
		</dependency>

		<dependency>
			<groupId>info.quantlab</groupId>
			<artifactId>numerical-methods-lecture</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
		</dependency>
	</dependencies>

	<build>
		<defaultGoal>clean install javadoc:javadoc</defaultGoal>
		<finalName>${project.artifactId}-${project.version}</finalName>
		<sourceDirectory>${src.main.java.dir}</sourceDirectory>
		<testSourceDirectory>${src.test.java.dir}</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${compiler-plugin.version}</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<compilerVersion>${java.version}</compilerVersion>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire-plugin.version}</version>
				<configuration>
					<forkCount>1</forkCount>
					<reuseForks>false</reuseForks>
					<argLine>-mx6G</argLine>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>${maven.checkstyle-plugin.version}</version>
				<configuration>
					<configLocation>checkstyle/finmath-checkstyle.xml</configLocation>
					<encoding>UTF-8</encoding>
					<consoleOutput>true</consoleOutput>
					<failsOnError>true</failsOnError>
					<linkXRef>false</linkXRef>
				</configuration>
				<executions>
					<execution>
						<id>validate</id>
						<phase>validate</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven.javadoc-plugin.version}</version>
					<configuration>
						<source>${envSource}</source>
						<doctitle>${project.name} (${project.version}) documentation</doctitle>
						<docfilessubdirs>true</docfilessubdirs>
						<header>
				   			<![CDATA[
							<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
							</script>
  				   			]]>
						</header>
						<links>
							<!-- links not compatible with JMPA -->
							<!-- <link>http://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/</link> -->
							<!-- <link>http://commons.apache.org/proper/commons-lang/javadocs/api-release/</link> -->
						</links>
						<detectLinks>false</detectLinks>
						<additionalOptions>
							<additionalOption>--allow-script-in-comments</additionalOption>
						</additionalOptions>
					</configuration>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.apache.maven.plugins
										</groupId>
										<artifactId>
											maven-checkstyle-plugin
										</artifactId>
										<versionRange>
											[3.1.2,)
										</versionRange>
										<goals>
											<goal>check</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<repositories>
		<!-- <repository> <id>github</id> <name>GitHub qntlb Apache Maven Packages</name> 
			<url>https://maven.pkg.github.com/qntlb/numerical-methods-computerarithmetic-exercise</url> 
			</repository> -->
		<repository>
			<id>lecture-maven-repo</id>
			<url>https://raw.githubusercontent.com/qntlb/numerical-methods-lecture/master/local-maven-repo</url>
		</repository>
	</repositories>

</project>
